### ISSUE TITLE
Адаптивность интерфейса

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/KinectV2TVInteraction#1]
Сейчас данный проект развернут на двух экранах, в кампусе МИРЭА, и кампусе МГУПИ
в первом случае разрешение экрана - 1920 на 1080
Во втором - в э1280 на 720

Сейчас все параметры размеров в приложении захардкожены, для МИРЭА в ветке master, для МГУПИ в ветке MGUPI

Необходимо привести интерфейс к адаптивному формату, который будет самостоятельно масштабироваться на различных экранах

**Comment by leonis13579** [comment]
Закрыто коммитом от 07.12.2020 с выпуском релиза v1.2.
