### ISSUE TITLE
Авто-сборка проекта на ТВ

### ISSUE THREAD

**Issue by MrWoWander** [RTUITLab/KinectV2TVInteraction#12]
Сделать билд, который при пуше в определенную ветку сам заливает новую версию приложения на большой экран
Так же можно сделать и с видео, играми - чтобы ручками самим не подключатся к ПК и не заменять файлы

**Comment by CAPCHIK** [comment]
Вот про игры хотел недавно предложить - приложение вполне может ходить в сервис со сборками (который в процессе поднятия) и скачивать новые бинарики например по ночам, ну или качать, а потом быстро аккуратно подменять папку.

Про обновление самого приложения - сложнее, ибо надо как-то ронять само приложение и запускать на нем новое.

Я делал такое в SC, с сервисом на windows server, там необходимо было останавливать и поднимать UI приложение. Готов поделиться опытом

**Comment by MrWoWander** [comment]
> 
> Про обновление самого приложения - сложнее, ибо надо как-то ронять само приложение и запускать на нем новое.
> 

Ну я думаю можно же как то сделать консольную команду в приложение, которая будет ронять саму себя

**Comment by CAPCHIK** [comment]
Можно, но потом надо сделать так, чтобы на месте этого приложения было новое, а этим должен управлять некий сторонний процесс, и вот с ним надо чуть чуть поколдовать

**Comment by CAPCHIK** [comment]
@Suput Надо бы этим заняться, не автодеплой на ПК, это пока не нужно, но по аналогии с https://github.com/RTUITLab/ITLab-Android/releases и https://github.com/RTUITLab/Excursion360-Web/releases сделать автопубликацию сборки по тегу

Плюс договоритесь с @bezlla каким образом будет подкладываться информация о версии проекта, её надо аккуратно показывать на главном экране в углу, в корневом меню то есть, где расписание новости игры и видео. Чтобы можно было в любой момент подойти и проверить, какая именно версия показывается. Можно просто создавать отдельный файл `build.json`, который пост фактум никто не будет редактировать, или можно компилировать с флагом, чтобы версия запекалась в Assembly, наизусть не помню, как это делать

**Comment by aforesaid** [comment]
Реализовано. Версия запекается при билде. Сейчас используется с Github Actions по релизным тегам.
