### ISSUE TITLE
Empty timetable

### ISSUE THREAD

**Issue by Suput** [RTUITLab/KinectV2TVInteraction#14]
Когда нет пар на какой-то из дней (сегодня или завтра), то лучше показывать не пустые строчки (кажется, как будто он грузит), а писать, какое-то сообщение "ПАР СЕГОДНЯ НЕТ"
Общее расписание, думаю, оставить таким, как есть сейчас

**Comment by aforesaid** [comment]
В какой-то из версий было исправлено.
