### ISSUE TITLE
Управление с приложения

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/KinectV2TVInteraction#2]
Есть готовое приложение на Flutter, которое может управлять параметрами проекта через сервер firebase https://github.com/RTUITLab/Screen-Remote

Необходимо реализовать прием управляющих команд

**Comment by leonis13579** [comment]
Создан файл настроек и класс, общающийся с ним. На какой бд по итогу делаем управление Экраном, на FireBase или на какой-то своей?

**Comment by CAPCHIK** [comment]
Управляющие сигналы шлются через Firebase, можешь запустить приложение, ссылка в первом комменте

**Comment by leonis13579** [comment]
@CAPCHIK, А можно перекатить оба приложения с FireBase на что-то свое и более независимое? К примеру не большой бек на Spring, развернутый на сервере лабы? Просто очень не хочется лезть в FireBase. 

(Если вопрос в написании сервера, то не проблема, сделаю сам и отлажу на проекте пульта. Благо опыт есть.)

**Comment by CAPCHIK** [comment]
В этом проекте Журавлев уже все сделал на firebase, и само приложение и сервис для перегонки сообщений (не берусь в тонкости формулировки, говорю про суть)

Так что можешь с ним списаться, узнать , что да как
