### ISSUE TITLE
Implement logging service

### ISSUE THREAD

**Issue by aforesaid** [RTUITLab/KinectV2TVInteraction#20]

**Comment by CAPCHIK** [comment]
Про логирование - подумай про логирование в облако, в сервисы по типу logstash, чтобы логи можно было наблюдать удаленно.
Туда же можно подумать про сбор метрик, например Prometheus
Просто на подумать

**Comment by aforesaid** [comment]
Насчёт логирования, было бы логичнее интегрироваться в систему логирования, которая уже используется нами. У нас есть такая?

**Comment by CAPCHIK** [comment]
О том и речь, что почти доделан ELK стек, соответственно потому и предлагаю logstash

**Comment by aforesaid** [comment]
Внедрен Serilog. Подключиться к ELK не составит проблем, достаточно будет лишь подтянуть библиотеку и поправить конфигурацию логгера.
