### ISSUE TITLE
Change license type

### ISSUE THREAD

**Issue by aforesaid** [RTUITLab/KinectV2TVInteraction#21]

**Comment by CAPCHIK** [comment]
О чем речь?

**Comment by aforesaid** [comment]
Глянь актуальную лицензию проекта, если это ок, тогда у меня вопросов нет.

**Comment by CAPCHIK** [comment]
Да, пара вопросов есть) Можешь списаться с Ченцовым по этому вопросу, они уже делали лицензию

**Comment by aforesaid** [comment]
Предлагаю рассмотреть что-нибудь классическое, по типу Apache v2.0 или MIT, и не тратить ресурсы на написание лицензии. Конечно, если это не нарушает права лабы на репозиторий.

**Comment by CAPCHIK** [comment]
Не поверишь, именно это тебе и кинут в ответ, с ними так же рассуждали и выбирали между ними. Сейчас не хочу вспоминать, как и к чему пришли, так что пообщайся сам)

**Comment by aforesaid** [comment]
В качестве лицензии был взят шаблон Apache v2.0.
