### ISSUE TITLE
Implement Kinect service to MVVM

### ISSUE THREAD

**Issue by aforesaid** [RTUITLab/KinectV2TVInteraction#42]

**Comment by CAPCHIK** [comment]
@bezlla Лучше не закрывать их таким образом, а просто в коммите второй строкой (чтобы в сводке не было видно) писать `close #42`, и когда коммит сам по себе окажется в ветке по умолчанию Issue все закроются

Так можно долго работать, в каждом отдельном коммите писать, что именно сделал, и потом пачкой они все закроются

Но **важно** именно на второй строке писать это, ибо к самому GIT эта информация не относится (гит понятия не имеет о Issue), и в основном комментарии пишешь текст нормальный, а потом на второй строке - служебную информацию.

**Comment by CAPCHIK** [comment]
Ну и плюс получается в каждом Issue можно отследить, как именно это Issue был реализован, что тоже полезно, ибо тут останется ссылка на коммит

**Comment by aforesaid** [comment]
Ты прав, я просто в коммите забыл указать.
