### ISSUE TITLE
Кэш новостей

### ISSUE THREAD

**Issue by MrWoWander** [RTUITLab/KinectV2TVInteraction#6]
Сделать возможность хранить часть новостей в кэше, для демонстрации новостей, если интернет будет отсутствовать. Обновлять кэш при открытии новостей и перед активации экрана после сна

**Comment by CAPCHIK** [comment]
Как предложение - обновлять кеш не при открытии новостей и перед активацией, а по таймеру, раз в пол часа например

Если обновлять перед открытием новостей - упадет время открытия, так как надо снаала залезть в интернет, потом открыть, если открывать из кеша, и параллельно стучаться в интернет - будет видно изменение новостей "на лету", что тоже спорно.

Если обновлять при открытии экрана после сна - возможно в этот момент как раз пропал интернет, и новости будут суточной давности (например)

Так что по нагрузке на ПО и надежности обновление раз в пол часа выглядит довольно стабильно и удобно.

**Comment by leonis13579** [comment]
Реализовано.

Сделана возможность выбора частоты обновления (в минутах) в json-е настроек. Производиться обновление в фоне (в отдельном потоке), однако при запуске приложения принудительно обновляется. Новости хранятся в json файле, лежащем на устройстве. В файле хранятся названия новостей, сама новость и фотографии к ней (в байтовом массиве).

**Comment by CAPCHIK** [comment]
Чтобы это Issue автоматически закрылось в коммите допиши второй строкой close #6, так при попадании коммита с таким сообщением закроется и сам Isuue
И в самом Issue будет отображаться, кто когда и каким коммитом закрыл этот Issue

**Comment by leonis13579** [comment]
Закрыто коммитом от 07.12.2020 с выпуском релиза v1.2.
