### ISSUE TITLE
App year

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/KinectV2TVInteraction#7]
Поменять год в нижнем правом углу с 2020 на 2021

"RTU IT Lab 2021"

**Comment by MrWoWander** [comment]
Предлагаю в дальнейшем автоматическое обновление даты. Либо по мере сборки проекта, либо чтобы приложение смотрело само, какой сейчас год

**Comment by leonis13579** [comment]
А разве там указывается не год сборки проекта? просто бредово получается, что нужно тогда каждый год обновлять проект для данного года. Я думал, что это из формата "since/est. 2020"

**Comment by MrWoWander** [comment]
> А разве там указывается не год сборки проекта? просто бредово получается, что нужно тогда каждый год обновлять проект для данного года. Я думал, что это из формата "since/est. 2020"
> 
> 

Ну это мы можем для себя решить. Мы это рассматриваем как дату последнего билда, или то, что проект ещё считается актуальным и мы его поддерживаем
Ну в любом случае, даже если смотреть по твоему сценарию, ты обновления выпускал в 21-м уже)

**Comment by leonis13579** [comment]
В новой версии дизайна отказался от записи года. Так что вопрос снят.
